### ISSUE TITLE
Are CMD commands supposed to be working?

### ISSUE THREAD

**Issue by IamNotARobot1** [Gloryness/tassomai-automation#48]
I can't find a way to make the command line work with tassomai automation to use with the schedular. Is it supposed to work or does it work for anyone else? I get this issue:

'github_db.exe' is not recognized as an internal or external command,
operable program or batch file.
ERROR:root:Traceback (most recent call last):
  File "app\main.py", line 90, in <module>
  File "gui\mainwindow.py", line 342, in __init__
  File "app\cache.py", line 26, in __init__
  File "base\common.py", line 40, in retreive_temp_data
  File "compress_json\compress_json.py", line 144, in load
  File "lzma.py", line 301, in open
  File "lzma.py", line 120, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\(username)\\AppData\\Local\\tassomai-automation\\temp.lzma'

**Comment by Gloryness** [comment]
add me on discord gloryy#0001 i'll see what i can do to help since it works for me
